# Generated by Django 6.1 on 2026-05-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="away_player_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_doubles_games",
                to="league.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="home_player_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_doubles_games",
                to="league.player",
            ),
        ),
    ]
